### PR TITLE
master: fixed compare of ldap_result return value

### PR DESCRIPTION
**Pull request by trammell**
I'm in the process of testing this to address an issue I'm seeing in a production system.  It looks right to me, but I'd appreciate more eyes on it.

### CODE REVIEW

**Comment by tatref** [comment]
It seems fine (same as https://github.com/threerings/openvpn-auth-ldap/issues/11?)

**Comment by apeschel** [comment]
I thought 0 indicates a success -- so shouldn't it be `< 0` and not `<=0`?

**Comment by apeschel** [comment]
:+1: This PR looks good to me and fixes a crash-causing bug.

**Comment by diranged** [comment]
Seriously ... this should get merged -- its been open nearly a year!

**Comment by manuvaldi** [comment]
+1

**Comment by tatref** [comment]
Unfortunately, I don't think the original authors are still developping this...

On a side note, has any of you managed to get the code to compile on any recent Linux?

**Pull request merged**
