### PR TITLE
support for RFC2307 groups

### PR DESCRIPTION
**Pull request by fredericve**
This commit converts  the patch in https://github.com/threerings/openvpn-auth-ldap/issues/7 to be compatible with the current master branch.

### CODE REVIEW

**Comment by samskivert** [comment]
You mind fielding this one @landonf ? I don't feel particularly qualified. :)

**Comment by landonf** [comment]
LGTM, as long as this here isn't a leak -- might need an autorelease:

https://github.com/threerings/openvpn-auth-ldap/pull/49/files#diff-6b63bb233e57531d2583d0a7a36726d4R539

`-[TRGroupConfig memberRFC2307BIS]` should probably also default to YES to maintain compatibility with existing deployed config files that assume rfc2307bis behavior.

**Comment by neutrinus** [comment]
This would solve many of my problems.  Any chance to get it merged?

**Comment by fredericve** [comment]
For completeness, we've been using this one in production since I opened the PR. We didn't see an increase in memory usage.

**Comment by k0ste** [comment]
Resolve #7

**Pull request merged**
